### ISSUE TITLE
Assertion errors when trying to convert Examples.ipynb into PDF

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/nbbrowserpdf#6]
I have latest `nbpresent` and `nbbrowserpdf` from master and just tried to generate a PDF using the "headless" mode server-side generation.  First I got an OSX warning asking if Python2.7 could connect to the Internet, then I immediately got a 500 server error (in browser) before I responded:

```bash
nbconvert failed: Command '['/Users/ijstokes/anaconda/envs/nbext/bin/python', '-m', 'nbbrowserpdf.exporters.pdf_capture', '/var/folders/77/y59g45c92dz_n71czgm8d67w0000gp/T/tmpWNrY4G']' returned non-zero exit status -6
```
and in the terminal output I got this combination of errors:

```bash
[I 15:32:23.886 NotebookApp] Kernel started: 3fc0eb60-e6db-43ab-9443-681ee8bcd54b
/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
[W 15:32:35.560 NotebookApp] Notebook Examples.ipynb is not trusted
[I 15:32:35.790 NotebookApp] Building PDF...
2015-12-04T15:32:36.608Z [INFO    ] Ghost: Initializing QT application
INFO:ghost:Initializing QT application
2015-12-04T15:32:37.438Z [INFO    ] Ghost<66fd8918-7e1e-446d-a86c-632c16d26f80>: Starting new session
INFO:ghost.66fd8918-7e1e-446d-a86c-632c16d26f80:Starting new session
2015-12-04T15:32:37.540Z [INFO    ] Ghost<66fd8918-7e1e-446d-a86c-632c16d26f80>: Opening http://localhost:9999/index.html
INFO:ghost.66fd8918-7e1e-446d-a86c-632c16d26f80:Opening http://localhost:9999/index.html
2015-12-04 15:32:37.599 python[9340:2419784] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /SourceCache/Foundation/Foundation-1154/Misc.subproj/NSUndoManager.m:340
2015-12-04 15:32:37.603 python[9340:2419784] +[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.
2015-12-04 15:32:37.620 python[9340:2419784] (
	0   CoreFoundation                      0x00007fff8658f03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8742676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8658ee1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8d60499b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff8d58664f +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 156
	5   AppKit                              0x00007fff8c623b95 -[NSApplication run] + 756
	6   libQtGui.4.8.7.dylib                0x0000000106feb532 _ZN26QEventDispatcherMacPrivate22ensureNSAppInitializedEv + 136
	7   libQtGui.4.8.7.dylib                0x0000000106fecab0 _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 968
	8   libQtCore.4.8.7.dylib               0x00000001064439cc _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 78
	9   QtCore.so                           0x000000010612ddf4 meth_QCoreApplication_processEvents + 164
	10  libpython2.7.dylib                  0x00000001000c39bd PyEval_EvalFrameEx + 24989
	11  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	12  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	13  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	14  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	15  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	16  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	17  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	18  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	19  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	20  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	21  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	22  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	23  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	24  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	25  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	26  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	27  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	28  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	29  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	30  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	31  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	32  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	33  libpython2.7.dylib                  0x000000010001dccd instancemethod_call + 333
	34  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	35  libpython2.7.dylib                  0x00000001000bc567 PyEval_CallObjectWithKeywords + 87
	36  libpython2.7.dylib                  0x00000001001047a7 t_bootstrap + 71
	37  libsystem_pthread.dylib             0x00007fff872b605a _pthread_body + 131
	38  libsystem_pthread.dylib             0x00007fff872b5fd7 _pthread_body + 0
	39  libsystem_pthread.dylib             0x00007fff872b33ed thread_start + 13
)
2015-12-04 15:32:37.621 python[9340:2419784] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /SourceCache/Foundation/Foundation-1154/Misc.subproj/NSUndoManager.m:340
2015-12-04 15:32:37.623 python[9340:2419784] An uncaught exception was raised
2015-12-04 15:32:37.623 python[9340:2419784] +[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.
2015-12-04 15:32:37.623 python[9340:2419784] (
	0   CoreFoundation                      0x00007fff8658f03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8742676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8658ee1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8d60499b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff8d58664f +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 156
	5   AppKit                              0x00007fff8c623c41 -[NSApplication run] + 928
	6   libQtGui.4.8.7.dylib                0x0000000106feb532 _ZN26QEventDispatcherMacPrivate22ensureNSAppInitializedEv + 136
	7   libQtGui.4.8.7.dylib                0x0000000106fecab0 _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 968
	8   libQtCore.4.8.7.dylib               0x00000001064439cc _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 78
	9   QtCore.so                           0x000000010612ddf4 meth_QCoreApplication_processEvents + 164
	10  libpython2.7.dylib                  0x00000001000c39bd PyEval_EvalFrameEx + 24989
	11  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	12  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	13  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	14  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	15  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	16  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	17  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	18  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	19  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	20  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	21  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	22  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	23  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	24  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	25  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	26  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	27  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	28  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	29  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	30  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	31  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	32  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	33  libpython2.7.dylib                  0x000000010001dccd instancemethod_call + 333
	34  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	35  libpython2.7.dylib                  0x00000001000bc567 PyEval_CallObjectWithKeywords + 87
	36  libpython2.7.dylib                  0x00000001001047a7 t_bootstrap + 71
	37  libsystem_pthread.dylib             0x00007fff872b605a _pthread_body + 131
	38  libsystem_pthread.dylib             0x00007fff872b5fd7 _pthread_body + 0
	39  libsystem_pthread.dylib             0x00007fff872b33ed thread_start + 13
)
2015-12-04 15:32:37.624 python[9340:2419784] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8658f03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8742676e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8658ee1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8d60499b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff8d58664f +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 156
	5   AppKit                              0x00007fff8c623c41 -[NSApplication run] + 928
	6   libQtGui.4.8.7.dylib                0x0000000106feb532 _ZN26QEventDispatcherMacPrivate22ensureNSAppInitializedEv + 136
	7   libQtGui.4.8.7.dylib                0x0000000106fecab0 _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 968
	8   libQtCore.4.8.7.dylib               0x00000001064439cc _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 78
	9   QtCore.so                           0x000000010612ddf4 meth_QCoreApplication_processEvents + 164
	10  libpython2.7.dylib                  0x00000001000c39bd PyEval_EvalFrameEx + 24989
	11  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	12  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	13  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	14  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	15  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	16  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	17  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	18  libpython2.7.dylib                  0x00000001000c3d10 PyEval_EvalFrameEx + 25840
	19  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	20  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	21  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	22  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	23  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	24  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	25  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	26  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	27  libpython2.7.dylib                  0x00000001000bea0a PyEval_EvalFrameEx + 4586
	28  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	29  libpython2.7.dylib                  0x00000001000c505b PyEval_EvalFrameEx + 30779
	30  libpython2.7.dylib                  0x00000001000c5ca3 PyEval_EvalCodeEx + 2115
	31  libpython2.7.dylib                  0x000000010003e1d0 function_call + 176
	32  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	33  libpython2.7.dylib                  0x000000010001dccd instancemethod_call + 333
	34  libpython2.7.dylib                  0x000000010000c7b2 PyObject_Call + 98
	35  libpython2.7.dylib                  0x00000001000bc567 PyEval_CallObjectWithKeywords + 87
	36  libpython2.7.dylib                  0x00000001001047a7 t_bootstrap + 71
	37  libsystem_pthread.dylib             0x00007fff872b605a _pthread_body + 131
	38  libsystem_pthread.dylib             0x00007fff872b5fd7 _pthread_body + 0
	39  libsystem_pthread.dylib             0x00007fff872b33ed thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[W 15:32:39.133 NotebookApp] 500 GET /nbconvert/browserpdf/Examples.ipynb?download=true (::1): nbconvert failed: Command '['/Users/ijstokes/anaconda/envs/nbext/bin/python', '-m', 'nbbrowserpdf.exporters.pdf_capture', '/var/folders/77/y59g45c92dz_n71czgm8d67w0000gp/T/tmpWNrY4G']' returned non-zero exit status -6
[E 15:32:39.135 NotebookApp] Exception in exception handler
    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 1450, in _execute
        self._handle_request_exception(e)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 1502, in _handle_request_exception
        self.send_error(e.status_code, exc_info=sys.exc_info())
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 978, in send_error
        self.finish()
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/site-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/json/encoder.py", line 209, in encode
        chunks = list(chunks)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/Users/ijstokes/anaconda/envs/nbext/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x106a00c90> is not JSON serializable

```
```

**Comment by bollwyvl** [comment]
Thanks for the report!

Perhaps related to this:

http://stackoverflow.com/questions/19070188/error-using-ghost-py-to-scrape-a-page

**Comment by ijstokes** [comment]
Sounds like the problem I had, but I don't understand what the stated "explanation" (which maybe is half-way to a solution?) is talking about.

**Comment by bollwyvl** [comment]
Just the quick googling. What is the source of your pyqt/pyside?

**Comment by bollwyvl** [comment]
Until we have an OSX build env, it will be hard to test from this side. But yeah, the browser in the python is going to talk to the network.

Here's a minimal dockerfile/compose I put together, just to prove to myself that stuff is working outside of my machine:
https://gist.github.com/bollwyvl/fedc3e37b9da43e9f14b

I do note that my extension, while installed, is not being enabled... @damianavila what dark magic must i perform to get my stuff working again? Seriously bad things happen if I set JUPYTER_CONFIG_DIR in the docker environment, as I imagine they do some stuff to the config to make everything work correctly.

**Comment by ijstokes** [comment]
@bollwyvl I didn't have `pyside` installed.  Would have have had some effect?  After I installed it, I now have these versions on my system (trace below):

```bash
(nbext)ijstokes@petawawa tmp (master) $ conda list | grep -e pyside -e pyqt
pyqt                      4.11.4                   py27_1    defaults
pyside                    1.1.2                    py27_1    defaults
```

However I still get the exception (OS X dialog with Python segfault message) even after having done this.  Below is a trace of my `pyqt pyside` update attempt (`pyqt` was the latest available)

```bash
(nbext)ijstokes@petawawa tmp (master) $ conda install pyqt pyside
Fetching package metadata: ....
Solving package specifications: .............
Package plan for installation in environment /Users/ijstokes/anaconda/envs/nbext:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    shiboken-1.1.2             |           py27_0         875 KB  defaults
    pyside-1.1.2               |           py27_1         5.2 MB  defaults
    ------------------------------------------------------------
                                           Total:         6.0 MB

The following NEW packages will be INSTALLED:

    pyside:   1.1.2-py27_1 defaults
    shiboken: 1.1.2-py27_0 defaults

Proceed ([y]/n)? y

Fetching packages ...
shiboken-1.1.2 100% |#########################################################################| Time: 0:00:00   1.55 MB/s
pyside-1.1.2-p 100% |#########################################################################| Time: 0:00:21 252.09 kB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################| 100%
```

**Comment by ijstokes** [comment]
I didn't answer your question clearly: I have pyside and pyqt from conda packages.

**Comment by bollwyvl** [comment]
Ghost.py requires one or the other, and handles the importing.

I was leaning towards recommending pyqt, as it is in anaconda, but ghost.py
prefers pyside... but only, perhaps, for licensing reasons?

I was just wondering, based on some of the tracebacks, if there were more
native libraries installed that were somehow interacting with the problem.

Anyhow... i got nothing. It's probably some way that ghost/i/tornado is
working with the various threads that doesn't happen on linux. I have also
had issues with windows.

In the meantime, I'm starting to add the tests described in #4. Perhaps by
the time I have them sorted, we'll have an OSX build slave and can start
observing the problem more directly.

**Comment by damianavila** [comment]
> I do note that my extension, while installed, is not being enabled... @damianavila what dark magic must i perform to get my stuff working again? Seriously bad things happen if I set JUPYTER_CONFIG_DIR in the docker environment, as I imagine they do some stuff to the config to make everything work correctly.

Which bad things are happening? How do you start the notebook in the docker file?

Something like  `JUPYTER_CONFIG_DIR=$CONDA_ENV_PATH/etc/jupyter jupyter notebook` should work...
